create table public.usuarios (
  id integer generated by default as identity primary key,
  email varchar(150) not null unique check (email = lower(email)),
  password_hash varchar(255),
  nombre_completo varchar(150) not null,
  telefono varchar(20),
  rol varchar(20) not null check (rol in ('dueno', 'barbero', 'cliente')),
  activo boolean not null default true
);

create unique index usuarios_cliente_telefono_unique
  on public.usuarios (telefono)
  where rol = 'cliente' and telefono is not null;

create table public.servicios (
  id integer generated by default as identity primary key,
  nombre varchar(150) not null,
  descripcion text,
  precio numeric(10, 2) not null check (precio >= 0),
  duracion_minutos integer not null check (duracion_minutos > 0),
  activo boolean not null default true
);

create table public.citas (
  id integer generated by default as identity primary key,
  cliente_id integer not null references public.usuarios(id),
  barbero_id integer not null references public.usuarios(id),
  servicio_id integer not null references public.servicios(id),
  fecha date not null,
  hora time without time zone not null,
  estado varchar(20) not null default 'confirmada'
    check (estado in ('confirmada', 'pendiente', 'completada', 'cancelada'))
);

create index citas_fecha_estado_idx on public.citas (fecha, estado);
create index citas_barbero_fecha_idx on public.citas (barbero_id, fecha);

alter table public.usuarios enable row level security;
alter table public.servicios enable row level security;
alter table public.citas enable row level security;

create or replace function public.crear_cita(
  p_customer_name varchar,
  p_phone varchar,
  p_date date,
  p_time time without time zone,
  p_service_id integer,
  p_barber_id integer
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_duration integer;
  v_customer_id integer;
  v_appointment_id integer;
begin
  if extract(isodow from p_date) = 7
    or p_time < time '09:00'
    or p_time >= time '19:00'
  then
    raise exception 'SLOT_TAKEN' using errcode = '23P01';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended('barber:' || p_barber_id::text || ':' || p_date::text, 0)
  );
  perform pg_advisory_xact_lock(hashtextextended('customer:' || p_phone, 0));

  select s.duracion_minutos
    into v_duration
    from public.servicios as s
    join public.usuarios as b
      on b.id = p_barber_id and b.rol = 'barbero' and b.activo
   where s.id = p_service_id and s.activo;

  if v_duration is null then
    raise exception 'SERVICE_OR_BARBER_UNAVAILABLE' using errcode = 'P0001';
  end if;

  if p_time + make_interval(mins => v_duration) > time '19:00' then
    raise exception 'SLOT_TAKEN' using errcode = '23P01';
  end if;

  if exists (
    select 1
      from public.citas as c
      join public.servicios as s on s.id = c.servicio_id
     where c.barbero_id = p_barber_id
       and c.fecha = p_date
       and c.estado in ('confirmada', 'pendiente')
       and c.hora < p_time + make_interval(mins => v_duration)
       and p_time < c.hora + make_interval(mins => s.duracion_minutos)
  ) then
    raise exception 'SLOT_TAKEN' using errcode = '23P01';
  end if;

  select u.id
    into v_customer_id
    from public.usuarios as u
   where u.rol = 'cliente' and u.telefono = p_phone
   for update;

  if v_customer_id is null then
    insert into public.usuarios (email, nombre_completo, telefono, rol)
    values (
      'booking.' || gen_random_uuid()::text || '@clientes.mcbarber.invalid',
      p_customer_name,
      p_phone,
      'cliente'
    )
    returning id into v_customer_id;
  else
    update public.usuarios
       set nombre_completo = p_customer_name
     where id = v_customer_id;
  end if;

  insert into public.citas (cliente_id, barbero_id, servicio_id, fecha, hora, estado)
  values (v_customer_id, p_barber_id, p_service_id, p_date, p_time, 'confirmada')
  returning id into v_appointment_id;

  return v_appointment_id;
end;
$$;

revoke all on function public.crear_cita(varchar, varchar, date, time without time zone, integer, integer) from public, anon, authenticated;
grant execute on function public.crear_cita(varchar, varchar, date, time without time zone, integer, integer) to service_role;
